import { useState, useEffect, useContext } from "react";
import useSWR from "swr";
import { useInView } from "react-intersection-observer";
import Head from "next/head";
import Home from "./Home/Home";
import { Data } from "../types/interfaces";
import Context from "../store/context";

function Reuse({
  photos,
  query = "",
  home,
  description,
  title,
}: {
  photos: Data[];
  query: string;
  home: boolean;
  description: string;
  title: string;
}) {
  const [fetchPhoto, setFetchPhoto] = useState(photos);
  const [page, setPage] = useState(2);

  const dataCtx = useContext(Context);

  const { ref, inView } = useInView({ threshold: 0.5 });

  const { data, error } = useSWR(
    `https://api.unsplash.com/photos?client_id=${process.env.NEXT_PUBLIC_API_KEY}&query=${query}&page=${page}&per_page=20`
  );

  useEffect(() => {
    if (inView) {
      if (data) {
        setFetchPhoto([...fetchPhoto, ...data]);

        setPage(page + 1);
      }
    }
    dataCtx.setApiData(fetchPhoto);
  }, [inView]);

  return (
    <section>
      <Head>
        <title>{title} | Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home
        refer={ref}
        photos={fetchPhoto}
        home={home}
        description={description}
        title={title}
      />
    </section>
  );
}

export default Reuse;
